# CSC 231: Computer Systems

**Syllabus**

- **Instructor**: Linh B. Ngo
- **Office**: UNA 138
- **Office Hours Fall 2023**:
  - MWF : 11:00AM-12:00PM (in-person and online)
  - TR  : 11:00AM-12:00PM (online)
  - Online Zoom link is posted in D2L's announcement page
- **Email**: lngo AT wcupa DOT edu
  - I will respond to emails within 24 hours during the work week. 
- **Phone**: 610-436-2595

## Course Information
- The course runs from August 28, 2023 until December 11, 2023. 
- There are two sections for the courses:
  - CSC 231-02: In-person, MWF 12:00PM - 12:50PM Anderson Hall 315
  - CSC 231-03: Online asynchronous. For this section, students are 
  not expected to attend the online Zoom session. 
- Recordings for topics will be embedded in the class' website. 
- An introductory recording for the class will be made available in 
the course's D2L page. 

## Required Materials

- **Dive into Systems** by Suzanna J. Matthews, Tia Newhall, and Kevin C. Webb. 
  - A free open-source online version of this book is available 
  at [https://diveintosystems.org](https://diveintosystems.org/)

- You are expected to have a computer system that meets the minimum 
expectations as outlined by West Chester University Information 
Services on the [Recommended Student Computer Configuration](https://www.wcupa.edu/distanceEd/techRequirements.aspx). You need a working web-camera and microphone.


## Resources and Accessibility

- For general technical support, students can contact WCU IT 
HelpDesk at 610-436-3350 or via email: helpdesk@wcupa.edu.
- For distance education support, students can contact WCU Distance 
Education Services at 610-436-3373 or via email: distanceed@wcupa.edu.
- A Discord server will be created and invitation link made available 
inside D2L. Technical questions specific to online competition platforms 
used in the course can be sent via email to the instructor or posted on 
the Discord server.


## Course Description
In this course, we will learn fundamental concepts of modern computer systems. 
Unlike courses in Computer Organizations, Operating Systems, and Computer Architecture, 
we will be approaching these concepts from the perspective of system users rather than 
system builders. This will help us to understand how various computer system components, 
including CPU, memory, storage, and networking, work. Throughout the course, we will learn 
to use assembler language and C language to explore and observe specifically how computer 
systems interpret and execute programs. With the knowledge learned from this course, you 
will be able to build programs that are more efficient and have better performance.

## Prerequisites
- CSC 142: Computer Science II
- MAT 151: Discrete Mathematics

## Learning Objectives

### Course Student Learning Outcomes (CSLO)
  1. Be able to understand and manipulate the byte-representation of 
  different data types (int, float, char …)
  2. Be able to understand simple segment of Assembler codes.
  3. Be able to understand how processes are loaded into memory and 
  memory placements of stack, heap, and code within the virtual memory.
  4. Be able to understand the tradeoff in accessing data stored 
  in various memory hierarchical levels.
  5. Be able to understand how simple network communication works 
  within the Linux operating system.
  6. Be able to understand how to perform various debugging and 
  optimization techniques.
  7. Be able to understand how layered service designs and API 
  works from a systems programming perspective.
### CS Program Objectives (CSPO)
  1. Be able to apply theory, techniques, and methodologies to create and/or 
  maintain high quality computing systems that function effectively and reliably 
  in the emerging and future information infrastructure (CSLO 1, 2, 3, 4, 5, 6, 7).
### CS/ABET Program Outcomes (ABET)
  1. ABET 1: Analyze a complex computing problem and to apply principles of 
  computing and other relevant disciplines to identify solutions (CSLO 1, 2, 3, 4).
  2. ABET 2: Design, implement, and evaluate a computing-based solution to meet 
  a given set of computing requirements in the context of the program’s 
  discipline (CSLO 5, 6, 7).
  
### Certificate in Computer Security Program Outcomes
1. Analyze and resolve security issues in network and computer 
systems to secure an IT infrastructure

## Assessments and Grading

### Method of Evaluation

```{list-table} Method of Evaluation
:header-rows: 1
:name: method-of-evaluation

* - Assessment
  - \% of Final Grade
  - Course Objectives Assessed
  - Program Objectives Assessed
  - ABET Objectives Assessed
* - Programming Assignment Sets
  - 35\%
  - SLO 1, 2
  - CSPO 1
  - ABET 1
* - Labs
  - 25\%
  - SLO 3, 4, 5, 6, 7
  - CSPO 1
  - ABET 1, 2
* - Quizzes
  - 20\%
  - SLO 1, 5
  - CSPO 1
  - ABET 1, 2
* - Participation
  - 5\%
  - SLO 1, 2, 3, 4
  - CSPO 1
  - ABET 1
* - Exams
  - 15\%
  - SLO 2, 3, 4, 5, 6, 7
  - CSPO 1
  - ABET 1, 2
```

### Grade Scale

| Numeric | Letter |
| ---------- | ----- |
| 100-93 |	A |
| 92-90	| A- |
| 89-87	| B+ |
| 86-83	| B |
| 82-80	| B- |
| 79-77	| C+ |
| 76-73	| C |
| 72-70	| C- |
| 69-67	| D+ |
| 66-63	| D |
| 62-60	| D- |
| <= 59	| F |

Refer to the [Grading Information section](https://catalog.wcupa.edu/undergraduate/academic-policies-procedures/grading-information/) 
section of the Undergraduate Catalog for description  of NG (No Grade), 
W, Z, and other grades. 

### Assessments

- Assignments: Writing and running programs written in C programming language, 
and demonstrating ability to read, understand, and modify Assembly/binary code.
  - Writing introductory C codes that demonstrate understanding of the language. 
  - Writing C codes that demonstrate understanding and the ability to manipulate
  the byte-representation of different data types (int, float, char …).
  - Demonstrate understanding by writing corresponding C codes that would translate
  to segment of Assembler codes given by the assignment.
  - Perform calculations to demonstrate understanding the tradeoff in accessing
  data stored in various memory levels.
  - Write a program that performs asynchronous communication tasks across a computer
  network.
- Labs: In the labs, students will learn to use command line tools and programs common
in the Linux operating systems for their programs. 
- Quiz and Exams: Multiple choice, code reading, and code correction are used to 
assess understanding of theoretical concepts necessary to support the tasks 
described in the assignments and labs. 

### Midterm and Final Exam

- The Midterm Exam will be disseminated in the last week of October. 
- Final Exam date will be scheduled according to the University’s Final 
Exam Schedule for Fall 2023.

### Lateness Policy:

- For lab submission, each late day (including weekends) will incur a 5\% penalty 
on the lab grade, up to a maximum of 50\% penalty. No late submission will be accepted 
after two weeks past the due date. 
- There is no late submission accept for assignment. Instead, the instructor will 
follow an mastery grading scheme approach as follows:
  - Each assignment has three versions 
    - The assignment's score is the highest score out of the three attempts. 
    - The versions contain additional work of the same difficulty level (just slightly!).
    - If you can't make it for the first version, keep going and try again. 
    - The final versions for all assignments are due on the last day of class. 



## University Policies 

### Academic & Personal Integrity
It is the responsibility of each student to adhere to the university’s standards 
for academic integrity. Violations of academic integrity include any act that 
violates the rights of another student in academic work, that involves misrepresentation 
of your own work, or that disrupts the instruction of the course. Other violations include 
(but are not limited to): cheating on assignments or examinations; plagiarizing, which 
means copying any part of another’s work and/or using ideas of another and presenting 
them as one’s own without giving proper credit to the source; selling, purchasing, or 
exchanging of term papers; falsifying of information; and using your own work from one 
class to fulfill the assignment for another class without significant modification. 
Proof of academic misconduct can result in the automatic failure and removal from this 
course. For questions regarding Academic Integrity, the No-Grade Policy, Sexual Harassment, 
or the Student Code of Conduct, students are encouraged to refer to the 
[Department Undergraduate Handbook](https://www.wcupa.edu/sciences-mathematics/computerScience/undergrad.aspx), 
the [Undergraduate Course Catalog](https://catalog.wcupa.edu/undergraduate/), 
the [Ram’s Eye View](https://www.wcupa.edu/_services/STU/ramsEyeView/), or 
the [University Website](https://www.wcupa.edu).  

### Students with Disabilities 
If you have a disability that requires accommodations under the Americans with 
Disabilities Act (ADA), please present your letter of accommodations and meet with me as 
soon as possible so that I can support your success in an informed manner. Accommodations 
cannot be granted retroactively. If you would like to know more about West Chester 
University’s Services for Students with Disabilities (OSSD), please visit them at 223 
Lawrence Center. Their phone number is 610-436-2564, their fax number is 610-436-2600, 
their email address is ossd@wcupa.edu, or visit the [OSSD website](https://www.wcupa.edu/universitycollege/ossd/). 
In an effort to assist students who either receive or may believe they are entitled 
to receive accommodations under the Americans with Disabilities Act and Section 504 of 
the Rehabilitation Act of 1973, the University has appointed a student advocate to be 
a contact for students who have questions regarding the provision of their 
accommodations or their right to accommodations. The advocate will assist any student 
who may have questions regarding these rights. The Director for Equity and Compliance/Title 
IX Coordinator has been designated in this role. Students who need assistance with 
their rights to accommodations should contact them at 610-436-2433.

The [University’s Americans with Disabilities policy](https://www.wcupa.edu/_admin/diversityEquityInclusion/adaPolicy.aspx) 
is available on the website.  If you encounter an area of this course that is not accessible to 
you, please contact me.  

### Excused Absences Policy 

Students are advised to carefully read and comply with the excused absences policy, including 
absences for university-sanctioned events, contained in the WCU Undergraduate Catalog. 
In particular, please note that the **responsibility for meeting academic requirements rests 
with the student**, that this policy does not excuse students from completing required academic 
work, and that professors can require a **fair alternative** to attendance on those days 
that students must be absent from class in order to participate in a University-Sanctioned Event.

### Reporting Incidents of Sexual Violence 
West Chester University and its faculty are committed to assuring a safe and productive 
educational environment for all students. In order to comply with the requirements of 
Title IX of the Education Amendments of 1972 and the University’s commitment to offering 
supportive measures in accordance with the new regulations issued under Title IX, the 
University requires faculty members to report incidents of sexual violence shared by 
students to the University's Title IX Coordinator. The only exceptions to the faculty 
member's reporting obligation are when incidents of sexual violence are communicated 
by a student during a classroom discussion, in a writing assignment for a class, or 
as part of a University-approved research project. Faculty members are obligated to 
report sexual violence or any other abuse of a student who was, or is, a child (a 
person under 18 years of age) when the abuse allegedly occurred to the person designated 
in the University Protection of Minors Policy. Information regarding the reporting of 
sexual violence and the resources that are available to victims of sexual violence is 
set forth at the [webpage for the Office of Diversity, Equity, and Inclusion](https://www.wcupa.edu/_admin/diversityEquityInclusion/sexualMisconduct/default.aspx).  

### Inclusive Learning Environment and Anti-Racist Statement

Diversity, equity, and inclusion are central to West Chester University’s mission as 
reflected in our [Mission Statement, Values Statement, Vision Statement](https://www.wcupa.edu/president/valuesAndVision.aspx) 
and [Strategic Plan: Pathways to Student Success](https://www.wcupa.edu/president/strategicPlan/default.aspx). 
We disavow racism and all actions that silence, threaten, or degrade historically 
marginalized groups in the U.S. We acknowledge that all members of this learning 
community may experience harm stemming from forms of oppression including but not 
limited to classism, ableism, heterosexism, sexism, Islamophobia, anti-Semitism, 
and xenophobia, and recognize that these forms of oppression are compounded by racism. 

Our core commitment as an institution of higher education shapes our expectation 
for behavior within this learning community, which represents diverse individual 
beliefs, backgrounds, and experiences. Courteous and respectful behavior, 
interactions, and responses are expected from all members of the University. 
We must work together to make this a safe and productive learning environment 
for everyone. Part of this work is recognizing how race and other aspects of 
who we are shape our beliefs and our experiences as individuals. It is not 
enough to condemn acts of racism. For real, sustainable change, we must stand 
together as a diverse coalition against racism and oppression of any form, 
anywhere, at any time. 

Resources for education and action are available through WCU’s 
[Office for Diversity, Equity, and Inclusion](https://www.wcupa.edu/_admin/diversityEquityInclusion/changeBeginsHere.aspx) 
(ODEI), DEI committees within departments or colleges, the student [ombudsperson](https://www.wcupa.edu/_services/STU/studentOmbuds/), 
and centers on campus committed to doing this work (e.g., [Dowdy Multicultural Center](https://www.wcupa.edu/_services/multicultural/), 
[Center for Women and Gender Equity](https://www.wcupa.edu/_services/women-gender-equity/), and the 
[Center for Trans and Queer Advocacy](https://www.wcupa.edu/_services/transAndQueer/)). 

Guidance on how to report incidents of discrimination and harassment is available at the University’s 
[Office of Diversity, Equity and Inclusion](https://www.wcupa.edu/_admin/diversityEquityInclusion/).

### Emergency Preparedness

All students are encouraged to sign up for the University’s free WCU ALERT service, 
which delivers official WCU emergency text messages directly to your cell phone. 
For more information, visit www.wcupa.edu/wcualert. To report an emergency, 
call the Department of Public Safety at 610-436-3311.

### Electronic Mail Policy 

It is expected that faculty, staff, and students activate and maintain regular 
access to University provided e-mail accounts. Official university communications, 
including those from your instructor, will be sent through your university e-mail 
account. You are responsible for accessing that mail to be sure to obtain official 
University communications. Failure to access will not exempt individuals from 
the responsibilities associated with this course.

## Resources for Student Success 

### Expectations for Student Success in Distance Education 

An online course uses technology to provide you, the student, with greater flexibility 
regarding when and where you learn.  To be a successful online learner you must 
capitalize on this increased flexibility by doing the following. 
- `Self-Motivation and Self-Discipline`: Active participation in online activities is expected. 
This means that you login to the course frequently, engage with the provided materials, and read 
and respond to communications in a timely and thoughtful manner.  Online courses require you to 
take more responsibility for your learning.    
- `Planning and Organization`: You will need disciplined work habits, effective time management 
skills, and the ability to work both alone and collaboratively if you wish to be successful 
in an online course.  You should expect to devote 9 to 12 hours per week to this course.  
You may find that you need to work harder than you would in a traditional lecture class.   
- `Communication Skills`: In an online course communication takes place primarily through 
the written word.  You need strong English reading and writing skills to express your 
thoughts.  Online courses also expect you to proactively reach out to your instructor 
for assistance when you need it.  Finally, pay attention to communication guidelines 
and be respectful of your fellow students when you communicate.        

### Minimum Student Technical Skills

You are expected to be competent in the use of computers, the World Wide Web, and commonly 
used software programs such as the Microsoft Office Suite of applications and Adobe PDF readers. 
In addition, you should be able to utilize a web-camera and microphone.  You should have a basic 
understanding of how to use the common elements of the university learning management system.

Students without experience using the university’s learning management system (Desire2Learn) 
can contact the Student Help Desk to arrange instruction, can contact Distance Education 
Support, or can complete tutorials in [Navigating Digital Learning](https://d2l.wcupa.edu/d2l/home/2513024). 

Hours for support services may vary.  Check their websites for times of operation.  

- General Technical Support: Contact the WCU IT Helpdesk at 610-436-3350 or email helpdesk@wcupa.edu
- Distance Education Support: Contact The Office of Digital Learning & Innovation at 610-436-3373 or email distanceed@wcupa.edu 
- Additional technical support information will be provided for tools as needed throughout the course.

### Accessibility Policies, Privacy Policies, and Support Site Information:

This course uses a variety of tools.  To access a tool’s accessibility and privacy policy, 
navigate to the [Distance Education Accessibility and Privacy Policies website](https://www.wcupa.edu/DistanceEd/resourcesandpolicies.aspx).  

### Student Academic and Support Services

Student academic and support services provided by the university can be found on the 
[Ram’s Eye View Services website](https://www.wcupa.edu/_services/STU/ramsEyeView/services.aspx).

### Library Resources for Distance Education Students

The West Chester University Library makes resources available to distance education students. 
Please review their [Library Services for Distance Students website](https://library.wcupa.edu/distance) 
for specific information.

## Course Topics and Schedules

- Quizzes are typically disseminated once evere two week. 
  - Assignments and Labs are due via D2L submission pages. 

```{list-table} Topics and Tentative Schedule
:header-rows: 1
:name: topic-schedule

* - Week
  - Topic
  - Assessments
* - 1
  - Introduction to Computer Systems 
  - Lab 1: Introduction to Linux (Due on Sep 24)
* - 
  - Introduction to C programming language
  - Assignment 1 (Due on Sep 16)
* - 2
  - Introduction to C (cont.)
  -
* - 3
  - Representing and manipulating information
  - Assignment 2 (Due on Oct 17)
* - 4
  - Representing and manipulating information (cont.)
  - 
* - 5
  - Representing and manipulating information (cont.)
  - Assignment 3 (Due on Oct 30)
* - 6
  - Advanced C 
  - Lab 2 (Due on Nov 6)
* - 7
  - Computer Architecture
  - 
* - 8 
  - Midterm
  - Assignment 4 (Due on Nov 20)
* - 9
  - Machine Language 
  - Lab 3 (Due on Nov 20)
* - 10
  - Machine Language (cont.)
  - 
* - 11
  - Memory hierarchy and cache memories
  - 
* - 12
  - Memory hierarchy and cache memories (cont.)
  - Lab 4 (Due on Dec 9)
* - 13
  - Memory hierarchy and cache memories (cont.)
  - Assignment 5 (Due on Dec 11)
* - 14 
  - Performance optimization (cont.)
  - 
* - 15
  - Performance optimization
  - Lab 5 (Due on Dec 12)
```

## Bibliography

1. Computer Systems, Warford, J., Fifth Edition, ISBN: 1284079635
2. Computer Systems: Digital Design, Fundamental of Computer Architecture 
and Assembly Language, Elahi, A., ISBN: 9783319667744
3. Computer Organization and Design, Patterson, D. and Hennessy, J., 
Fifth Edition, ISBN: 0124077269
4. The Elements of Computing Systems: Building a Modern Computer from First 
Principles, Nisan, N. and Schocken, S., ISBN: 0262640686
5. Computer System Architecture, Mano, M., Third Edition, ISBN 0131755633
6. Introduction to Computing Systems: From Bits and Gates to C and Beyond, 
Patt, Y. and Patel, S., Second Edition, ISBN: 0072467509
7. Computer Systems: An Integrated Approach to Architecture and Operating 
Systems, Ramachandran, U. and Leahy Jr., W., ISBN 0312486137
