---
title: "About Me"
---

I am an associate professor in the [Computer Science Department](https://www.wcupa.edu/sciences-mathematics/computerScience/) 
at [West Chester University of Pennsylvania](https://www.wcupa.edu/). This is 
my academic website, where I provide and update information related to my current 
research and teaching activities.  

My general research focuses on the areas of distributed systems, big data engineering, 
and computer science education. More specifically, I am interested in research problems that 
from real world scenarios and can create learning opportunities to students, particularly 
undergraduates. I also am interested in interdisciplinary collaborative work where research 
computing technologies are combined with domain knowledge to address socially relevant 
research problems.

I completed my PhD in Computer Science in December of 2011 at the University of Arkansas in Fayetteville. From 2012 to 2013, I worked as a postdoctoral researcher at the School of Computing, Clemson University. From 2013 to 2015, I became a research associate and Deputy Director of the Big Data Systems Lab, led by Dr. Amy Apon, at the School of Computing. Since 2015, I have joined Clemson University’s Cyberinfrastructure and Technology Integration (CITI) Department within the Clemson Computing and Information Technology Group as the Director of Data Science. At the same time, I have maintained my affiliation with the School of Computing as a Research Assistant Professor with teaching responsibilities and research participation. Starting August 2018, I have been appointed Assistant Professor of Computer Science at West Chester University of Pennsylvania.

Outside of work, I enjoy books, computer games, and sport, not necessarily in this order. I read a lot of books, but mainly in the fantasy genres. Similarly, I play mostly RPG games, although I also enjoy turn-based strategies and FPS when my time is limited. Soccer and basketball have been my favorite activities since highschool.

```{r}
1 + 1
```
